package com.kenzie.appserver.controller.model;

import com.fasterxml.jackson.annotation.JsonProperty;

import javax.validation.constraints.NotEmpty;

//Hello team members! This class doesn't have evidenceId or timestamp because
//those fields aren't user input; they are generated by the service
//also caseId isn't required because it is a part of the path in the request
//the author field is the only one that can be empty. elise
public class EvidenceCreateRequest {

    @JsonProperty("author")
    private String author;

    @NotEmpty
    @JsonProperty("description")
    private String description;

    @NotEmpty
    @JsonProperty("location")
    private String location;

    @NotEmpty
    @JsonProperty("timeDate")
    private String timeDate;

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getTimeDate() {
        return timeDate;
    }

    public void setTimeDate(String timeDate) {
        this.timeDate = timeDate;
    }
}
